// src/locales/en.js
export default {
  header: {
    title: "Astana AI Trips",
    subtitle: "Future-ready travel planning"
  },
  nav: {
    home: "Home",
    videoGuides: "Video Guides",
    itineraries: "Itineraries",
    cityInsights: "City Insights",
    getStarted: "Get Started"
  },
  hero: {
    title: "Explore Astana",
    subtitle: "Intelligent day plans, local insights, cost-aware suggestions — all generated by AI in seconds.",
    inputPlaceholder: "Describe your perfect day: 'Romantic day under 25k' or 'Family with kids, cultural sights'",
    generateButton: "Generate My Day",
    generating: "✨ AI Planning...",
    features: {
      aiPlans: "AI-Powered Plans",
      realPlaces: "Real Astana Places",
      downloadPDF: "Download PDF"
    }
  },
  itinerary: {
    aiItinerary: "AI Itinerary",
    enterPreferences: "Enter your preferences to start",
    total: "Total",
    aiGenerated: "✨ AI Generated",
    downloadPDF: "Download PDF"
  },
  footer: {
    copyright: "© {year} Astana AI Trips",
    privacy: "Privacy",
    terms: "Terms",
    contact: "Contact"
  },
  videoGuides: {
    hero: {
      title: "Astana Video Guides",
      subtitle: "See Before You Go",
      description: "Visual guides to navigate Astana like a local"
    }
  },
  categories: {
    allGuides: "All Guides",
    publicTransport: "Public Transport",
    walkingRoutes: "Walking Routes",
    driving: "Driving",
    culture: "Culture"
  },
  transport: {
    bus: "Bus",
    walking: "Walking",
    taxi: "Taxi",
    car: "Car",
    metro: "Metro",
    "light-rail": "Light Rail"
  },
  guides: {
    abuDhabi: {
      title: "Abu Dhabi Plaza Route",
      description: "Smart navigation to the city's tallest building with shopping and dining",
      category: "public",
      duration: "0:38",
      landmarks: ["Abu Dhabi Plaza", "Observation Deck", "Luxury Mall"],
      difficulty: "Easy",
      aiTip: "Visit the observation deck at sunset for panoramic city views",
      estimatedTime: "30 min",
      cost: "110₸"
    },
    atryauBridge: {
      title: "Atyrau Bridge - Central Park Access",
      description: "Scenic routes to the iconic pedestrian bridge with park connections",
      category: "public",
      duration: "0:45",
      landmarks: ["Atyrau Bridge", "Central Park", "Fountain Square"],
      difficulty: "Easy",
      aiTip: "Best photos from the southeast corner during golden hour - perfect for silhouette shots against the city skyline",
      estimatedTime: "25 min",
      cost: "110₸"
    },
    operaPhilharmonic: {
      title: "Astana Opera & Philharmonic",
      description: "Cultural tour of Astana's premier music venues and performing arts centers",
      category: "culture",
      duration: "4:20",
      landmarks: ["Astana Opera House", "Kazakhstan National Philharmonic", "Abai Square"],
      difficulty: "Easy",
      aiTip: "Check performance schedules in advance and dress smart-casual for evening shows",
      estimatedTime: "3-4 hours",
      cost: "5,000-15,000₸ (depending on show tickets)"
    },
    baursak: {
      title: "Traditional Kazakh Baursak",
      description: "Try Kazakh baursak - delicious fried dough pastry",
      category: "culture",
      duration: "3:45",
      landmarks: ["Traditional Kitchen", "Local Market", "Cooking Workshop"],
      difficulty: "Easy",
      aiTip: "Serve baursak warm with kaymak (clotted cream) and homemade jam for the authentic Kazakh tea experience",
      estimatedTime: "1-2 hours",
      cost: "2,000-5,000₸ (ingredients)"
    },
    kurt: {
      title: "Traditional Kazakh Kurt",
      description: "Discover kurt - traditional dried cheese balls, a staple of nomadic cuisine",
      category: "culture",
      duration: "4:20",
      landmarks: ["Traditional Yurt", "Dairy Workshop", "Nomadic Heritage Site"],
      difficulty: "Easy",
      aiTip: "Kurt is perfect for long journeys - it's lightweight, nutritious and doesn't spoil. Crumble it into soups or enjoy as a snack with tea",
      estimatedTime: "1-2 hours",
      cost: "1,000-3,000₸"
    },
    kokpar: {
      title: "Traditional Kazakh Kokpar",
      description: "Experience kokpar - exciting traditional horseback game with deep nomadic roots",
      category: "culture",
      duration: "5:15",
      landmarks: ["Equestrian Center", "Traditional Arena", "Horse Stables"],
      difficulty: "Medium",
      aiTip: "Best viewed during national holidays and festivals. Arrive early to get good seating and watch the pre-game ceremonies",
      estimatedTime: "2-3 hours",
      cost: "Free to watch (tournaments may have ticket fees)"
    },
    asyk: {
      title: "Traditional Kazakh Asyk Game",
      description: "Play asyk - ancient bone throwing game popular among Kazakh nomads",
      category: "culture",
      duration: "2:30",
      landmarks: ["Traditional Playground", "Cultural Center", "Outdoor Game Area"],
      difficulty: "Easy",
      aiTip: "Perfect for family gatherings and celebrations. The game improves hand-eye coordination and is enjoyed by all ages",
      estimatedTime: "30-60 minutes",
      cost: "500-2,000₸ (asyk set)"
    },
    aulaCafe: {
      title: "AULA Cafe & Historic Center",
      description: "Charming cafe experience combined with historic landmarks walk",
      category: "cafe",
      duration: "3:45",
      landmarks: ["AULA Cafe", "Bayterek Tower", "Presidential Park", "Kazakhstan History Museum"],
      difficulty: "Easy",
      aiTip: "Visit AULA Cafe in the afternoon for the best coffee and pastries, then enjoy sunset views from Bayterek",
      estimatedTime: "2-3 hours",
      cost: "4,000-8,000₸"
    },
    lightRail: {
      title: "Astana Light Rail Transit Tour",
      description: "Efficient city exploration using Astana's modern light rail system",
      category: "transit",
      duration: "5:30",
      landmarks: ["Light Rail Stations", "Nurly Zhol Station", "Bayterek Tower Station", "EXPO Station"],
      difficulty: "Easy",
      aiTip: "Use the LRT during off-peak hours (10AM-4PM) for the most comfortable ride and best photo opportunities",
      estimatedTime: "4-5 hours",
      cost: "500₸ (LRT day pass)"
    },
    circus: {
      title: "Astana Circus & Entertainment District",
      description: "Family-friendly entertainment featuring the stunning Astana Circus building and surrounding attractions",
      category: "entertainment",
      duration: "4:15",
      landmarks: ["Astana Circus", "Circus Fountain Square", "Entertainment District", "Family Park"],
      difficulty: "Easy",
      aiTip: "Check the circus schedule for matinee shows - perfect for families with children and better pricing",
      estimatedTime: "3-4 hours",
      cost: "2,000-5,000₸ (show tickets)"
    },
    nationalMuseum: {
      title: "National Museum of Kazakhstan",
      description: "Explore Kazakhstan's rich history and cultural heritage in the magnificent National Museum",
      category: "public",
      duration: "4:15",
      landmarks: ["National Museum", "Bayterek Tower", "Independence Square"],
      difficulty: "Easy",
      aiTip: "Visit on weekdays to avoid crowds and take advantage of free guided tours at 11AM and 3PM. Don't miss the Hall of Gold on the 3rd floor",
      estimatedTime: "2-3 hours",
      cost: "1,500₸ (adult ticket)"
    },
    ailand: {
      title: "Ailand Astana",
      description: "Visit Ailand - exciting indoor entertainment and amusement center in Astana",
      category: "culture",
      duration: "3:50",
      landmarks: ["Ailand Entertainment Center", "Indoor Rides", "Game Zones", "Food Court"],
      difficulty: "Easy",
      aiTip: "Perfect for families with children. Visit during weekdays for shorter queues and check their website for special family package deals",
      estimatedTime: "3-4 hours",
      cost: "5,000-15,000₸ (depending on activities)"
    }
  }
};
