import { useState } from "react";
import { motion } from "framer-motion";
import { Link } from 'react-router-dom';

// AI-powered itinerary generator
async function generateItineraryData(query = '', lang = 'en') {
  try {
    // IMPORTANT: Use the correct endpoint
    const API_ENDPOINT = '/api/gemini'; // Changed from /api/free-ai
    
    // Simplified prompt that works better
    const prompts = {
      en: `Create a one-day Astana itinerary for: "${query}". 
           Format as JSON: {
             "title": "string",
             "items": [
               {"time": "9:00 AM", "place": "Place Name", "cost": "5000₸", "description": "Brief description"}
             ]
           }
           Total budget: 400,000₸ max.`,
      ru: `Создай однодневный маршрут по Астане для: "${query}".
           Формат JSON: {
             "title": "string",
             "items": [
               {"time": "9:00", "place": "Название места", "cost": "5000₸", "description": "Краткое описание"}
             ]
           }
           Бюджет: максимум 400,000₸.`,
      kz: `Астанаға бір күндік маршрут жаса: "${query}".
           JSON пішімі: {
             "title": "string",
             "items": [
               {"time": "9:00", "place": "Орын атауы", "cost": "5000₸", "description": "Қысқа сипаттама"}
             ]
           }
           Бюджет: ең көбі 400,000₸.`
    };

    console.log('📤 Sending request to:', API_ENDPOINT);
    console.log('📝 Prompt:', prompts[lang].substring(0, 100) + '...');
    
    const response = await fetch(API_ENDPOINT, {
      method: 'POST',
      headers: { 
        'Content-Type': 'application/json',
        'Accept': 'application/json'
      },
      body: JSON.stringify({ 
        prompt: prompts[lang]
      })
    });

    console.log('📥 Response status:', response.status);
    
    if (!response.ok) {
      const errorText = await response.text();
      console.error('❌ Server error response:', errorText);
      throw new Error(`Server error ${response.status}`);
    }

    const data = await response.json();
    console.log('📦 Response data:', data);
    
    if (!data.success) {
      throw new Error(data.error || 'API request failed');
    }
    
    const aiText = data.response;
    console.log('🤖 AI Response:', aiText);
    
    // Try to extract JSON
    let jsonMatch = aiText.match(/```json\n([\s\S]*?)\n```/) || 
                   aiText.match(/\{[\s\S]*\}/);
    
    if (!jsonMatch) {
      console.error('No JSON found in:', aiText);
      throw new Error('No valid JSON in AI response');
    }
    
    const jsonStr = jsonMatch[0].replace(/```json\n|\n```/g, '');
    const aiResponse = JSON.parse(jsonStr);

    if (aiResponse.title && aiResponse.items && Array.isArray(aiResponse.items)) {
      // Calculate total
      const total = aiResponse.items.reduce((acc, item) => {
        const cost = parseInt(item.cost?.replace(/[^0-9]/g, '')) || 0;
        return acc + cost;
      }, 0);

      return {
        title: aiResponse.title,
        items: aiResponse.items,
        total: `${total.toLocaleString()}₸`,
        source: 'ai'
      };
    } else {
      throw new Error('Invalid itinerary format');
    }

  } catch (error) {
    console.error('💥 API error:', error);
    throw new Error(`Failed to generate: ${error.message}`);
  }
}

// PDF Download function
function downloadPDF(itinerary, lang = 'en') {
  import('html2pdf.js').then((html2pdf) => {
    const translations = {
      en: { totalCost: 'Total Estimated Cost', enjoy: 'Enjoy your day in Astana! 🎉', generatedOn: 'Generated on' },
      ru: { totalCost: 'Общая стоимость', enjoy: 'Приятного дня в Астане! 🎉', generatedOn: 'Создано' },
      kz: { totalCost: 'Жалпы бағасы', enjoy: 'Астанадағы күніңіз сәтті өтсін! 🎉', generatedOn: 'Жасалған күні' }
    };
    const t = translations[lang];

    const content = `
      <div style="font-family: Arial, sans-serif; padding: 20px; max-width: 800px; margin: 0 auto;">
        <div style="text-align: center; margin-bottom: 30px; border-bottom: 2px solid #00bcd4; padding-bottom: 20px;">
          <h1 style="font-size: 28px; font-weight: bold; color: #333; margin: 0 0 10px 0;">${itinerary.title}</h1>
          <div style="font-size: 18px; color: #666; margin: 10px 0;">${t.totalCost}: ${itinerary.total}</div>
          <div style="color: #888; font-size: 14px;">Generated by Astana AI Trips</div>
        </div>
        
        ${itinerary.items.map((item) => `
          <div style="margin: 20px 0; padding: 15px; border-left: 4px solid #00bcd4; background: #f9f9f9;">
            <div style="display: flex; justify-content: between; align-items: start; margin-bottom: 8px;">
              <span style="font-weight: bold; color: #0288d1; font-size: 16px; min-width: 60px;">${item.time}</span>
              <div style="flex: 1;">
                <div style="font-size: 18px; font-weight: bold; color: #333; margin-bottom: 5px;">${item.place}</div>
                ${item.description ? `<div style="font-size: 14px; color: #555; line-height: 1.4;">${item.description}</div>` : ''}
              </div>
              <span style="font-weight: bold; color: #d32f2f; font-size: 16px; margin-left: 15px;">${item.cost}</span>
            </div>
          </div>
        `).join('')}
        
        <div style="text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #888; font-size: 14px;">
          <p>${t.enjoy}</p>
          <p>${t.generatedOn} ${new Date().toLocaleDateString()}</p>
        </div>
      </div>
    `;

    const element = document.createElement('div');
    element.innerHTML = content;
    document.body.appendChild(element);

    const options = {
      margin: 10,
      filename: `Astana-Itinerary-${new Date().getTime()}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2, useCORS: true },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
    };

    html2pdf.default().set(options).from(element).save().then(() => {
      document.body.removeChild(element);
    });
  }).catch(error => console.error('Error loading html2pdf:', error));
}

export default function Home() {
  const [query, setQuery] = useState("");
  const [itinerary, setItinerary] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [tilt, setTilt] = useState({ rotateX: 0, rotateY: 0, scale: 1 });
  const [lang, setLang] = useState('en');

  async function generateItinerary() {
    if (!query.trim()) return;
    setLoading(true);
    setError("");
    try {
      const data = await generateItineraryData(query, lang);
      setItinerary(data);
    } catch (error) {
      setError(error.message);
    } finally {
      setLoading(false);
    }
  }

  function handleDownload() {
    if (itinerary) downloadPDF(itinerary, lang);
  }

  const texts = {
    en: {
      placeholder: "Describe your perfect day: 'Romantic day under 25k' or 'Family with kids, cultural sights'",
      generate: "Generate My Day",
      aiGenerated: "✨ AI Generated",
      enterPrefs: "Enter your preferences to start",
      hero: <>Explore <span className="animated-gradient heading-font">Astana</span> the AI-curated way.</>,
      subHero: "Intelligent day plans, local insights, cost-aware suggestions — all generated by AI in seconds."
    },
    ru: {
      placeholder: "Опишите идеальный день: 'Романтический день до 25k' или 'Семья с детьми, культурные места'",
      generate: "Создать Мой День",
      aiGenerated: "✨ Сгенерировано AI",
      enterPrefs: "Введите предпочтения, чтобы начать",
      hero: <>Изучайте <span className="animated-gradient heading-font">Астану</span> с помощью AI.</>,
      subHero: "Интеллектуальные планы на день, советы местных жителей, рекомендации по бюджету — всё сгенерировано AI за секунды."
    },
    kz: {
      placeholder: "Күніңізді сипаттаңыз: '25k астында романтикалық күн' немесе 'Балалы отбасы, мәдени орындар'",
      generate: "Күнімді Жасау",
      aiGenerated: "✨ AI арқылы жасалды",
      enterPrefs: "Бастау үшін таңдауларыңызды енгізіңіз",
      hero: <>AI арқылы <span className="animated-gradient heading-font">Астананы</span> зерттеңіз.</>,
      subHero: "Ақылды күндік жоспарлар, жергілікті кеңестер, бюджетке сай ұсыныстар — бәрі секундтар ішінде AI арқылы."
    }
  };

  return (
    <main className="min-h-screen text-white antialiased">
      {/* Background omitted for brevity */}
      <header className="max-w-7xl mx-auto px-6 py-6 flex items-center justify-between">
  <div className="flex items-center gap-3">
    {/* Logo/Brand - make it clickable */}
    <Link to="/" className="flex items-center gap-3 hover:opacity-80 transition-opacity">
      <div className="w-10 h-10 rounded-full bg-gradient-to-tr from-cyan-400 to-purple-500 shadow-lg flex items-center justify-center text-black font-bold">AI</div>
      <div>
        <div className="text-lg font-semibold tracking-wide">Astana AI Trips</div>
        <div className="text-xs text-slate-300">Future-ready travel planning</div>
      </div>
    </Link>
  </div>

  {/* Navigation links */}
  <nav className="flex items-center gap-6">
    <Link to="/" className="text-slate-300 hover:text-white transition-colors text-sm font-medium">Home</Link>
    <Link to="/videos" className="text-slate-300 hover:text-white transition-colors text-sm font-medium">Video Guides</Link>
    <Link to="/insights" className="text-slate-300 hover:text-white transition-colors text-sm font-medium">City Insights</Link>

    {/* Language switcher */}
    <div className="flex items-center gap-2 ml-4">
      <button onClick={() => setLang('en')} className={`px-3 py-1 rounded ${lang==='en' ? 'bg-cyan-400 text-black' : 'bg-white/10'}`}>EN</button>
      <button onClick={() => setLang('ru')} className={`px-3 py-1 rounded ${lang==='ru' ? 'bg-cyan-400 text-black' : 'bg-white/10'}`}>RU</button>
      <button onClick={() => setLang('kz')} className={`px-3 py-1 rounded ${lang==='kz' ? 'bg-cyan-400 text-black' : 'bg-white/10'}`}>KZ</button>
    </div>
  </nav>
</header>

      <section id="hero" className="max-w-6xl mx-auto px-6 pt-10 pb-20 grid grid-cols-1 md:grid-cols-12 gap-8 items-center">
        <div className="md:col-span-7">
          <motion.h1 className="text-4xl md:text-6xl font-extrabold leading-tight heading-font">{texts[lang].hero}</motion.h1>
          <motion.p className="mt-4 text-slate-300 max-w-xl">{texts[lang].subHero}</motion.p>

          <div className="mt-8 flex gap-3 flex-col sm:flex-row">
            <input
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder={texts[lang].placeholder}
              className="flex-1 rounded-lg py-3 px-4 bg-white/5 placeholder:text-slate-300 focus:outline-none focus:ring-2 focus:ring-cyan-400 text-white"
            />
            <button onClick={generateItinerary} disabled={loading || !query.trim()}
              className="rounded-lg px-6 py-3 bg-gradient-to-r from-cyan-400 to-violet-500 text-black font-semibold shadow-lg disabled:opacity-50 disabled:cursor-not-allowed">
              {loading ? "✨ AI Planning..." : texts[lang].generate}
            </button>
          </div>

          {error && <div className="mt-4 p-3 rounded-lg bg-red-500/20 border border-red-500/30 text-red-300 text-sm">{error}</div>}
        </div>

        <div className="md:col-span-5">
          {/* Itinerary card with tilt */}
          <div style={{ perspective: 1200 }}>
            <motion.div
              initial={{ scale: 0.98, opacity: 0 }}
              animate={{ rotateX: tilt.rotateX, rotateY: tilt.rotateY, scale: tilt.scale, opacity: 1 }}
              transition={{ type: 'spring', stiffness: 140, damping: 20 }}
              onMouseMove={(e) => {
                const rect = e.currentTarget.getBoundingClientRect();
                const x = e.clientX - rect.left;
                const y = e.clientY - rect.top;
                const cx = rect.width / 2;
                const cy = rect.height / 2;
                setTilt({ rotateX: -((y - cy) / cy) * 6, rotateY: ((x - cx) / cx) * 8, scale: 1.03 });
              }}
              onMouseLeave={() => setTilt({ rotateX: 0, rotateY: 0, scale: 1 })}
              className="glass card-tilt rounded-2xl p-5 shadow-2xl border border-white/5"
            >
              <div className="flex items-start justify-between">
                <div>
                  <div className="text-sm text-slate-300">{texts[lang].aiGenerated}</div>
                  <div className="text-xl font-semibold mt-2">{itinerary ? itinerary.title : texts[lang].enterPrefs}</div>
                </div>
                {itinerary && <div className="text-right text-slate-400">Total <div className="text-white font-bold">{itinerary.total}</div></div>}
              </div>

              <div className="mt-4 space-y-3">
                {(itinerary ? itinerary.items : new Array(3).fill(0)).map((it, idx) => (
                  <div key={idx} className="flex items-start justify-between p-3 rounded-lg bg-white/2">
                    <div className="flex-1">
                      <div className="flex items-center gap-2">
                        <span className="font-mono text-cyan-300 text-xs">{it ? it.time : "--:--"}</span>
                        <div className="font-semibold text-sm">{it ? it.place : texts[lang].enterPrefs}</div>
                      </div>
                      {it && it.description && <div className="text-xs text-slate-300 mt-1">{it.description}</div>}
                    </div>
                    <div className="text-sm font-medium ml-2">{it ? it.cost : "—"}</div>
                  </div>
                ))}
              </div>

              {itinerary && (
                <div className="mt-5 flex items-center justify-between">
                  <div className="text-xs text-slate-300">{texts[lang].aiGenerated}</div>
                  <button onClick={handleDownload} className="px-3 py-2 rounded bg-gradient-to-r from-cyan-400 to-violet-500 text-black font-semibold text-sm shadow-lg hover:opacity-90 transition-opacity">
                    Download PDF
                  </button>
                </div>
              )}
            </motion.div>
          </div>
        </div>
      </section>

      <footer className="max-w-6xl mx-auto px-6 mt-14 py-8 text-sm text-slate-400 flex items-center justify-between">
        <div>© {new Date().getFullYear()} Astana AI Trips</div>
        <div className="flex gap-4">
          <a href="#">Privacy</a>
          <a href="#">Terms</a>
          <a href="#">Contact</a>
        </div>
      </footer>
    </main>
  );
}
