// components/astana_ai_landing_prototype.jsx
import { useState } from "react";
import { motion } from "framer-motion";
import { Link } from 'react-router-dom';

// AI-powered itinerary generator ONLY
// CHANGE THIS in your frontend component:
async function generateItineraryData(query = '') {
  try {
    // Use relative path for Vercel serverless function
    const API_ENDPOINT = `${import.meta.env.VITE_API_URL}/api/free-ai`;    
    const response = await fetch(API_ENDPOINT, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        prompt: `Create a one-day Astana itinerary for: "${query}". 
Include times, places, costs in KZT. 
Return valid JSON: {"title": "string", "items": [{"time": "string", "place": "string", "cost": "string", "description": "string"}]}`
      })
    });

    if (!response.ok) {
      throw new Error(`Server error ${response.status}`);
    }

    const data = await response.json();
    
    // Vercel function returns { response: "..." }
    const aiText = data.response;
    const jsonMatch = aiText.match(/\{[\s\S]*\}/);
    
    if (!jsonMatch) {
      throw new Error('No JSON found in AI response');
    }

    const aiResponse = JSON.parse(jsonMatch[0]);
    
    if (aiResponse.title && aiResponse.items && Array.isArray(aiResponse.items)) {
      const total = aiResponse.items.reduce((acc, item) => {
        const cost = parseInt(String(item.cost).replace(/[^0-9]/g, '')) || 0;
        return acc + cost;
      }, 0);
      
      return {
        title: aiResponse.title,
        items: aiResponse.items,
        total: `${total.toLocaleString()}₸`,
        source: 'ai'
      };
    } else {
      throw new Error('Invalid itinerary format from AI');
    }

  } catch (error) {
    console.error('API error:', error);
    throw new Error(`Failed to generate itinerary: ${error.message}`);
  }
}

// PDF Download function


// PDF Download function
function downloadPDF(itinerary) {
  // Import html2pdf dynamically to avoid SSR issues
  import('html2pdf.js').then((html2pdf) => {
    const content = `
      <div style="font-family: Arial, sans-serif; padding: 20px; max-width: 800px; margin: 0 auto;">
        <div style="text-align: center; margin-bottom: 30px; border-bottom: 2px solid #00bcd4; padding-bottom: 20px;">
          <h1 style="font-size: 28px; font-weight: bold; color: #333; margin: 0 0 10px 0;">${itinerary.title}</h1>
          <div style="font-size: 18px; color: #666; margin: 10px 0;">Total Estimated Cost: ${itinerary.total}</div>
          <div style="color: #888; font-size: 14px;">Generated by Astana AI Trips</div>
        </div>
        
        ${itinerary.items.map((item, index) => `
          <div style="margin: 20px 0; padding: 15px; border-left: 4px solid #00bcd4; background: #f9f9f9;">
            <div style="display: flex; justify-content: between; align-items: start; margin-bottom: 8px;">
              <span style="font-weight: bold; color: #0288d1; font-size: 16px; min-width: 60px;">${item.time}</span>
              <div style="flex: 1;">
                <div style="font-size: 18px; font-weight: bold; color: #333; margin-bottom: 5px;">${item.place}</div>
                ${item.description ? `<div style="font-size: 14px; color: #555; line-height: 1.4;">${item.description}</div>` : ''}
              </div>
              <span style="font-weight: bold; color: #d32f2f; font-size: 16px; margin-left: 15px;">${item.cost}</span>
            </div>
          </div>
        `).join('')}
        
        <div style="text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #888; font-size: 14px;">
          <p>Enjoy your day in Astana! 🎉</p>
          <p>Generated on ${new Date().toLocaleDateString()}</p>
        </div>
      </div>
    `;

    // Create a temporary container
    const element = document.createElement('div');
    element.innerHTML = content;
    document.body.appendChild(element);

    const options = {
      margin: 10,
      filename: `Astana-Itinerary-${new Date().getTime()}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2, useCORS: true },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
    };

    html2pdf.default().set(options).from(element).save().then(() => {
      document.body.removeChild(element);
    });
  }).catch(error => {
    console.error('Error loading html2pdf:', error);
    // Fallback to HTML download
    fallbackDownload(itinerary);
  });
}

// Fallback function if PDF generation fails
function fallbackDownload(itinerary) {
  const content = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>${itinerary.title}</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 20px; max-width: 800px; margin: 0 auto; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #00bcd4; padding-bottom: 20px; }
        .title { font-size: 28px; font-weight: bold; color: #333; margin-bottom: 10px; }
        .total { font-size: 18px; color: #666; margin: 10px 0; }
        .item { margin: 20px 0; padding: 15px; border-left: 4px solid #00bcd4; background: #f9f9f9; }
        .time { font-weight: bold; color: #0288d1; font-size: 16px; }
        .place { font-size: 18px; font-weight: bold; color: #333; margin-bottom: 5px; }
        .cost { color: #d32f2f; font-weight: bold; font-size: 16px; }
        .description { color: #555; font-size: 14px; line-height: 1.4; }
        .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #888; }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="title">${itinerary.title}</div>
        <div class="total">Total Estimated Cost: ${itinerary.total}</div>
        <div>Generated by Astana AI Trips</div>
      </div>
      
      ${itinerary.items.map(item => `
        <div class="item">
          <div style="display: flex; justify-content: space-between; align-items: start;">
            <span class="time">${item.time}</span>
            <div style="flex: 1; margin: 0 15px;">
              <div class="place">${item.place}</div>
              ${item.description ? `<div class="description">${item.description}</div>` : ''}
            </div>
            <span class="cost">${item.cost}</span>
          </div>
        </div>
      `).join('')}
      
      <div class="footer">
        <p>Enjoy your day in Astana! 🎉</p>
        <p>Generated on ${new Date().toLocaleDateString()}</p>
      </div>
    </body>
    </html>
  `;

  const blob = new Blob([content], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `Astana-Itinerary-${new Date().getTime()}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export default function Home() {
  const [query, setQuery] = useState("");
  const [itinerary, setItinerary] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [tilt, setTilt] = useState({ rotateX: 0, rotateY: 0, scale: 1 });

  async function generateItinerary() {
    if (!query.trim()) return;
    
    setLoading(true);
    setError("");
    try {
      const data = await generateItineraryData(query);
      setItinerary(data);
    } catch (error) {
      console.error("Error generating itinerary:", error);
      setError(error.message);
    } finally {
      setLoading(false);
    }
  }

  function handleDownload() {
    if (itinerary) {
      downloadPDF(itinerary);
    }
  }

  return (
    <main className="min-h-screen text-white antialiased">
      <div className="pointer-events-none fixed inset-0 -z-10 overflow-hidden">
        <svg className="absolute left-0 top-0 w-[1400px] opacity-10 -translate-y-1/4" viewBox="0 0 1000 500" preserveAspectRatio="none">
          <defs>
            <linearGradient id="g1" x1="0" x2="1">
              <stop offset="0%" stopColor="#00ffff" stopOpacity="0.35" />
              <stop offset="100%" stopColor="#9b5cff" stopOpacity="0.12" />
            </linearGradient>
          </defs>
          <path d="M0,100 C200,0 400,200 600,100 C800,0 1000,200 1200,100 L1200 0 L0 0 Z" fill="url(#g1)" />
        </svg>

        <motion.div
          className="absolute -left-60 top-1/4 w-[520px] h-[520px] rounded-full blur-3xl opacity-30"
          style={{ background: "linear-gradient(135deg,#6ee7b7,#60a5fa)" }}
          animate={{ x: [0, 20, 0], y: [0, -10, 0] }}
          transition={{ duration: 12, repeat: Infinity }}
        />

        <motion.div
          className="absolute right-[-120px] bottom-[-80px] w-[420px] h-[420px] rounded-full blur-3xl opacity-25"
          style={{ background: "linear-gradient(135deg,#c084fc,#fb7185)" }}
          animate={{ x: [0, -20, 0], y: [0, 10, 0] }}
          transition={{ duration: 15, repeat: Infinity }}
        />
      </div>

      <header className="max-w-7xl mx-auto px-6 py-6 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-full bg-gradient-to-tr from-cyan-400 to-purple-500 shadow-lg flex items-center justify-center text-black font-bold">AI</div>
          <div>
            <div className="text-lg font-semibold tracking-wide">Astana AI Trips</div>
            <div className="text-xs text-slate-300">Future-ready travel planning</div>
          </div>
        </div>
        <nav className="hidden md:flex items-center gap-6 text-sm text-slate-300">
          <a href="#features" className="hover:text-white transition">Features</a>
          <a href="#experiences" className="hover:text-white transition">Experiences</a>
          <a href="#testimonials" className="hover:text-white transition">Testimonials</a>
          <Link to="/videos" className="hover:text-white transition">Video Guides</Link>
          <a href="#start" className="px-4 py-2 rounded bg-gradient-to-r from-cyan-400 to-violet-500 text-black font-medium">Get Started</a>
        </nav>
      </header>

      <section id="hero" className="max-w-6xl mx-auto px-6 pt-10 pb-20 grid grid-cols-1 md:grid-cols-12 gap-8 items-center">
        <div className="md:col-span-7">
          <motion.h1 initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.08 }} className="text-4xl md:text-6xl font-extrabold leading-tight heading-font">
            Explore <span className="animated-gradient heading-font">Astana</span>
            <br /> <span className="text-slate-300">the AI-curated way.</span>
          </motion.h1>

          <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.18 }} className="mt-4 text-slate-300 max-w-xl">
            Intelligent day plans, local insights, cost-aware suggestions — all generated by AI in seconds.
          </motion.p>

          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.25 }} className="mt-8 flex gap-3 flex-col sm:flex-row">
            <input
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="Describe your perfect day: 'Romantic day under 25k' or 'Family with kids, cultural sights'"
              className="flex-1 rounded-lg py-3 px-4 bg-white/5 placeholder:text-slate-300 focus:outline-none focus:ring-2 focus:ring-cyan-400 text-white"
            />
            <button 
              onClick={generateItinerary} 
              disabled={loading || !query.trim()}
              className="rounded-lg px-6 py-3 bg-gradient-to-r from-cyan-400 to-violet-500 text-black font-semibold shadow-lg disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {loading ? "✨ AI Planning..." : "Generate My Day"}
            </button>
          </motion.div>

          {error && (
            <div className="mt-4 p-3 rounded-lg bg-red-500/20 border border-red-500/30">
              <div className="text-red-300 text-sm">{error}</div>
            </div>
          )}

          <div className="mt-6 flex items-center gap-4 text-sm text-slate-400">
            <span className="inline-flex items-center gap-2 px-3 py-1 rounded bg-white/3">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none">
                <path d="M12 2v10l3 3" stroke="white" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
              AI-Powered Plans
            </span>

            <span className="inline-flex items-center gap-2 px-3 py-1 rounded bg-white/3">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none">
                <path d="M21 10v6a2 2 0 0 1-2 2H5" stroke="white" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round" />
                <path d="M7 10V6a5 5 0 0 1 10 0v4" stroke="white" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
              Real Astana Places
            </span>

            <span className="inline-flex items-center gap-2 px-3 py-1 rounded bg-white/3">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none">
                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" stroke="white" strokeWidth="1.2"/>
                <path d="M14 2v6h6" stroke="white" strokeWidth="1.2"/>
              </svg>
              Download PDF
            </span>
          </div>
        </div>

        <div className="md:col-span-5">
          <div style={{ perspective: 1200 }}>
            <motion.div
              initial={{ scale: 0.98, opacity: 0 }}
              animate={{ rotateX: tilt.rotateX, rotateY: tilt.rotateY, scale: tilt.scale, opacity: 1 }}
              transition={{ type: 'spring', stiffness: 140, damping: 20 }}
              onMouseMove={(e) => {
                const rect = e.currentTarget.getBoundingClientRect();
                const x = e.clientX - rect.left;
                const y = e.clientY - rect.top;
                const cx = rect.width / 2;
                const cy = rect.height / 2;
                const rotateY = ((x - cx) / cx) * 8;
                const rotateX = -((y - cy) / cy) * 6;
                setTilt({ rotateX, rotateY, scale: 1.03 });
              }}
              onMouseLeave={() => setTilt({ rotateX: 0, rotateY: 0, scale: 1 })}
              className="glass card-tilt rounded-2xl p-5 shadow-2xl border border-white/5"
            >
            <div className="flex items-start justify-between">
              <div>
                <div className="text-sm text-slate-300">AI Itinerary</div>
                <div className="text-xl font-semibold mt-2">
                  {itinerary ? itinerary.title : "Enter your preferences to start"}
                </div>
              </div>
              {itinerary && (
                <div className="text-right text-slate-400">
                  Total <div className="text-white font-bold">{itinerary.total}</div>
                </div>
              )}
            </div>

            <div className="mt-4 space-y-3">
              {(itinerary ? itinerary.items : new Array(3).fill(0)).map((it, idx) => (
                <div key={idx} className="flex items-start justify-between p-3 rounded-lg bg-white/2">
                  <div className="flex-1">
                    <div className="flex items-center gap-2">
                      <span className="font-mono text-cyan-300 text-xs">{it ? it.time : "--:--"}</span>
                      <div className="font-semibold text-sm">{it ? it.place : "Enter preferences to generate"}</div>
                    </div>
                    {it && it.description && (
                      <div className="text-xs text-slate-300 mt-1">{it.description}</div>
                    )}
                  </div>
                  <div className="text-sm font-medium ml-2">{it ? it.cost : "—"}</div>
                </div>
              ))}
            </div>

            {itinerary && (
              <div className="mt-5 flex items-center justify-between">
                <div className="text-xs text-slate-300">✨ AI Generated</div>
                <button 
                  onClick={handleDownload}
                  className="px-3 py-2 rounded bg-gradient-to-r from-cyan-400 to-violet-500 text-black font-semibold text-sm shadow-lg hover:opacity-90 transition-opacity"
                >
                  Download PDF
                </button>
              </div>
            )}
          </motion.div>
            </div>
        </div>
      </section>

      <footer className="max-w-6xl mx-auto px-6 mt-14 py-8 text-sm text-slate-400 flex items-center justify-between">
        <div>© {new Date().getFullYear()} Astana AI Trips</div>
        <div className="flex gap-4">
          <a href="#">Privacy</a>
          <a href="#">Terms</a>
          <a href="#">Contact</a>
        </div>
      </footer>
    </main>
  );
}
